[package]
name = "libopenraw"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# libopenraw-sys = "0.1"
libopenraw-sys = { path = "../libopenraw-sys" }